### ISSUE TITLE
Maximize is broken in 1.2 (Wayland)

### ISSUE THREAD

**Issue by Ubiquitine** [sgicic/Shortcuts-for-KDE-s-built-in-tiling-manager#1]
## Description
With the script is enabled (v1.2), maximizing a window either does not do anythin  if the window is tiled, or changes the window geometry in a very strange way.
Tested this in VirtualBox with no other KWin scripts enabled.

## Screen casts
[Tiled to maximized](https://github.com/sgicic/returnToTile/assets/3274951/b80f5785-378b-48fe-ae7d-dc1b039eb415)
[Regular to maximized](https://github.com/sgicic/returnToTile/assets/3274951/6c5713ec-c4db-45d0-b894-947587ed1d89)

## System info
Operating System: KDE neon 6.0
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.5.0-35-generic (64-bit)
Graphics Platform: Wayland
Processors: 4 × Intel® Core™ i9-10900 CPU @ 2.80GHz
Memory: 15.6 GiB of RAM
Graphics Processor: SVGA3D; build: RELEASE; LLVM;
Manufacturer: innotek GmbH
Product Name: VirtualBox
System Version: 1.2
##
I really like the idea, and hope that the script would work under Wayland eventually.

**Comment by sgicic** [comment]
Huh, I'm using arch and it's working without issues on wayland. Might be an issue with KDE neon, I'll try too look into it when I find the time.

**Comment by Ubiquitine** [comment]
I tested it on my Thinkpad running Arch+KDE+Wayland - The behavior is the same as described in the report.
## System Info:
Operating System: Arch Linux 
KDE Plasma Version: 6.0.4
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.0
Kernel Version: 6.6.30-2-lts (64-bit)
Graphics Platform: Wayland
Processors: 16 × 13th Gen Intel® Core™ i7-1360P
Memory: 31.0 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: LENOVO
Product Name: 21HDA002CD
System Version: ThinkPad T14 Gen 4a

**Comment by sgicic** [comment]
Thank you for testing, I will look into it. 
It's a bit weird since it works on my laptop and desktop, both using the same plasma, kde framework and qt version as your arch machine does. 

I have an idea what it might be though, I'll report back when I get to the bottom of it.

**Comment by sgicic** [comment]
The bug should be fixed now. Do you mind trying it out before it publish it again on the kde store?
You can clone this repo and install it with the following command:
kpackagetool6 --type=KWin/Script -i /path/to/returnToTile

**Comment by Ubiquitine** [comment]
Thank you for a quick fix!
I can confirm now on my laptop the script works as expected.
Even more! it works properly with other scripts like Maximize6, which is AWESOME.

**Comment by sgicic** [comment]
Nice, thx again for pointing out the bug. I will close this for now.
Be sure to download the newest version from the KDE store, since I fixed a minor bug in the meantime as well.
Also, I would appreciate if you could leave a little review on the store page :).
